### ISSUE TITLE
first release?

### ISSUE THREAD

**Issue by eksperimental** [phoenixframework/phoenix_view#1]
I am reviewing the docs for the Phoenix guide, and I would like to link to the docs.
Is there any planned release in the near feature?
If note I can leave an internal note and update later the docs when the first version of this library is published.
Thank you.

**Comment by josevalim** [comment]
You should use simply `Phoenix.View` in the guides and ExDoc will link to it accordingly (if it is a dependency or bundled internally). The next release will happen on Phoenix v1.6.

**Comment by eksperimental** [comment]
I did. Now it  is a (Git) dependency. ExDoc links to hexdocs.pm but the package hasn't been published. But if it is going to be published by the release of Phoenix 1.6 it is all good then.
