### ISSUE TITLE
Migration guide doesn't address controller breakage

### ISSUE THREAD

**Issue by boringcactus** [phoenixframework/phoenix_view#19]
I'm trying to migrate a Phoenix.View to Phoenix.Component as described in [the migration guide](https://hexdocs.pm/phoenix_view/Phoenix.View.html#module-migrating-to-phoenix-component).

A small obstacle is that the guide says `embed_template "../templates/my"` but the correct code seems to be `embed_templates "../templates/my/*"`.

The larger obstacle is that `Phoenix.Controller.render/3` breaks because `MyAppWeb.MyView.render/2` is undefined, and the guide doesn't offer any way to resolve this problem. The guide should explain what to do to handle this.

**Comment by josevalim** [comment]
It is hard to say why your view breaks without looking at it. If it uses either one of Phoenix.View or Phoenix.Component and embeds the correct templates, then it should work. Can you post the view with error message and full stack trace?

also can you send a PR for the embed_template mistake?

**Comment by boringcactus** [comment]
Ahhh, `Phoenix.Controller.render/3` was breaking because I wasn't on the 1.7 RC, and it wasn't clear from the documentation that this would only work in 1.7.

**Comment by boringcactus** [comment]
And it looks like the function name was fixed in #18 and just isn't on HexDocs since it hasn't been included in a release yet. Added the `/*` in #20.
