### ISSUE TITLE
Phoenix.view.render_to_string/3 not working for text files

### ISSUE THREAD

**Issue by michaelkuk** [phoenixframework/phoenix_view#6]
## System
Elixir 1.12.2 - OTP 24
phoenix 1.6.6
phoenix_view 1.1.0

ArchLinux 5.15.7-arch1-1

## Problem

`Phoenix.View.render_to_string/3` fails when template filename does not have `.html.(h)eex` extension with the following stacktrace:

```
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not an iodata term

    :erlang.iolist_to_binary({:safe, ["Hello from TEXT\n"]})
    (phoenix_view 1.1.0) lib/phoenix/view.ex:480: Phoenix.View.render_to_string/3
```

This behavior is consistent whether I use template files or define render methods directly in view module.

### example
```elixir
defmodule SomeAppWeb.EmailView do
  @moduledoc """
  Email view
  """

  use SomeAppWeb, :view

  # WORKS!
  # iex > Phoenix.View.render(SomeAppWeb.EmailView, "contact_form.html", %{})
  #   "Hello from HTML\n"
  def render("contact_form.html", assigns) do
    ~H"""
    Hello from HTML
    """
  end

  # DOES NOT WORK!
  # iex > Phoenix.View.render(SomeAppWeb.EmailView, "contact_form.text", %{})
  #   ** (ArgumentError) errors were found at the given arguments:
  #
  # * 1st argument: not an iodata term
  #
  #   :erlang.iolist_to_binary({:safe, ["Hello from TEXT\n"]})
  #   (phoenix_view 1.1.0) lib/phoenix/view.ex:480: Phoenix.View.render_to_string/3
  def render("contact_form.text", assigns) do
    ~H"""
    Hello from TEXT
    """
  end
end
```

## Expectation
`Phoenix.View.render_to_string/3` should render `heex` regardless of the extension.

**Comment by josevalim** [comment]
Correct, ~H, as the name implies, returns a HTML based data structure. You can use regular heredocs or use EEx directly. You can use `~H"" |> Phoenix.HTML.html_escape |> Phoenix.HTML.safe_to_string` to get a string out of it.

**Comment by josevalim** [comment]
`~H` is going to be incompatible with context, it is not only about the output. For example, think about this: what if you want to write < or > or " in the email? In `~H`, those will be HTML escaped, and your textual email will be wrong. You need to use a template specific for text. Maybe Bamboo can provide a simple teex template (text EEx) that is mostly EEx, but using the HTML one is going to fail in other ways.

**Comment by josevalim** [comment]
Or, as I mentioned, use a heredoc. :)
