### ISSUE TITLE
Dialyzer is complaining after version update

### ISSUE THREAD

**Issue by thiagogsr** [phoenixframework/phoenix_view#8]
After these changes: https://github.com/phoenixframework/phoenix_view/compare/v1.1.0...v1.1.1

Dialyzer started complaining that `template_not_found/2` has no local return:

```
lib/namespace_web/views/error_view.ex:2:no_return
Function template_not_found/2 has no local return.
________________________________________________________________________________
lib/namespace_web/views/layout_view.ex:2:no_return
Function template_not_found/2 has no local return.
________________________________________________________________________________
done (warnings were emitted)
Halting VM with exit status 2
```

It complains about this method for every single `:view` file.

Should we add this method to all view files?

**Comment by josevalim** [comment]
Can you please check if it is address on master?

**Comment by balexand** [comment]
I'm also experiencing this. These dialyzer errors can be reproduced by generating a brand new Phoenix project with `mix phx.new example --no-assets --no-ecto`, adding `{:dialyxir, "~> 1.0", only: [:dev], runtime: false}` to the deps, and running `mix dialyzer`. 

I've tried updating the `phoenix_view` package to use master and I still get the error.

Thanks.

**Comment by tank-bohr** [comment]
The story behind this is described here https://github.com/phoenixframework/phoenix_view/pull/7

> It complains about this method for every single :view file.

This is something I've completely missed. I naively thought it'd affect only `ErrorView.` Now it looks very tricky. I have no idea how workaround this issue :(

**Comment by josevalim** [comment]
Please try again, it should be good now.

@tank-bohr I am not sure how to support your use case. :(

**Comment by thiagogsr** [comment]
It's indeed good now :-) 

```
done (passed successfully)
```

**Comment by bobwaycott** [comment]
Just want to chime in, fwiw, that I, too, ran into this issue last night with `1.1.1`, and can verify I no longer have `dialyzer` failures when I set `phoenix_view` as a dep from `master`.

**Comment by josevalim** [comment]
Shipped/ Thanks!
